### ISSUE TITLE
Constant values of all 28 possible pieces

### ISSUE THREAD

**Issue by sugyan** [rust-shogi-crates/shogi_core#17]
To simplify coding the value of pieces each time, I want to define it as a constant like this:

```rust
const BFU: Piece = Piece::new(PieceKind::Pawn, Color::Black);
```

But `shogi_core::Piece::new` cannot be called with in constants.
There are only 28 kinds of values at most, and it is helpful if they are defined as constant values.

https://github.com/HiraokaTakuya/apery_rust/blob/a7288919fd8d410e0365bf4395b13e03c672c2ec/src/types.rs#L910-L937

**Comment by koba-e964** [comment]
I couldn't agree more! So I think there are two problems here:
1. `Piece::new(kind, color)` is simply tedious to type. Can be resolved by defining constants.
2. All those functions (`new`, `from_**`, ...) should have been `const` in the first place, but I missed that.

## To be determined
- Names of these constants. Because this crate supports conversion into strings in USI format, USI-style names like `B_P` or `B_PR` (P for *promoted*) may sound consistent.
